#################################################
#
#  Configuration
#
#################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  packages: !include_dir_named packages

config:
logbook:
conversation:
history:
map:
hassio:
sun:
ios:
recorder:

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret network_key

discovery:
  ignore:
    - plex_mediaserver

updater:
  include_used_components: true

logger:
  default: info
  logs:
    custom_components: debug

lutron_caseta_pro:
    bridges:
      - host: !secret lutron_host_ip

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client
  username: !secret mqtt_user
  password: !secret mqtt_pass

http:
  base_url: !secret http_address
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret api_password

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
  - name: tiles
    sidebar_title: Tiles
    sidebar_icon: mdi:view-dashboard
    url_path: tiles
    config:
      entities:
        - entity: input_boolean.switch1
          label: Switch 1

input_boolean:
  e8t1:
  e8t2:
  e8t3:
  e8t4:
  dummy_tiles:
  switch1:

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  expose_by_default: false
  entities:
    input_boolean.e8t1:
      hidden: false
    input_boolean.e8t2:
      hidden: false
    input_boolean.e8t3:
      hidden: false
    input_boolean.e8t4:
      hidden: false

light:
  - platform: flux_led
    automatic_add: True
    devices:
      192.168.1.102:
        name: flux_led
        mode: rgb
  - platform: group
    name: Bedroom Lamp
    entities:
      - light.hue_bedroom_lamp_1
      - light.hue_bedroom_lamp_2

hue:
  bridges:
    - host: !secret hue_host_ip
      allow_unreachable: true

xiaomi_aqara:
  gateways:
    - mac: 78:11:dc:b7:dc:e0
      host: !secret xiaomi_host
      key: !secret xiaomi_key

sensor:
  - platform: uscis
    case_id: !secret USCIS_case
    name: USCIS

#remote:
#  - platform: harmony
#    name: Living Room
#    host: !secret harmony_host
#    activity: Watch TV
