homeassistant:
  customize:
    light.flux_led:
      friendly_name: LED strip
    climate.thermostat_cool:
      icon: mdi:snowflake
    climate.thermostat_heat:
      icon: mdi:fire
    group.all_automations:
      hidden: false
    group.all_devices:
      hidden: false
    group.all_lights:
      hidden: false
    group.all_locks:
      hidden: false
    group.all_remotes:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_switches:
      hidden: false

