automation:
  - alias: Home Assistant Startup
    id: Home_Assistant_Startup
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.notify
        data:
          message: Home Assistant is up
